### ISSUE TITLE
YouTube Music not playing

### ISSUE THREAD

**Issue by benblb** [music-assistant/hass-music-assistant#1774]
### What version of Music Assistant has the issue?

2.0.0b81

### The problem

YouTube music will not play or load any previously unloaded albums, playlists, etc. Already synced data is present, but no audio will stream. 

### How to reproduce

Tried to re-add YTM as a new provider and disable the old one; got the same error. To reproduce, try using YTM. 

### Relevant log output

```
2024-01-08 22:52:32.829 INFO (ThreadPoolExecutor-0_0) [pychromecast.controllers] Receiver:Launching app CC1AD845
2024-01-08 22:52:34.305 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 473, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 263, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 309, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 333, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 69, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 187, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 438, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 267, in get_item
    return await self.get_track(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 314, in get_track
    if track_obj := await get_track(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 94, in get_track
    return await asyncio.to_thread(_get_song)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 73, in _get_song
    track_obj = ytm.get_song(videoId=prov_track_id, signatureTimestamp=signature_timestamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 622, in get_song
    response = self._send_request(endpoint, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 230, in _send_request
    headers=self.headers,
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 215, in headers
    self._headers["authorization"] = self._token.as_auth()
                                     ^^^^^^^^^^^
AttributeError: 'YTMusic' object has no attribute '_token'
2024-01-08 22:52:34.344 WARNING (Thread-12) [music_assistant.providers.chromecast] Load media failed: 1 - error code: 104
2024-01-08 22:52:40.310 INFO (ThreadPoolExecutor-0_0) [pychromecast] Quitting current app
2024-01-08 22:52:40.310 INFO (ThreadPoolExecutor-0_0) [pychromecast.controllers] Receiver:Stopping current app 'CC1AD845'
2024-01-08 22:55:41.708 ERROR (MainThread) [music_assistant.webserver] [140116062708816] Error handling message: CommandMessage(message_id=15, command='music/artists/get_artist', args={'item_id': '603', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 187, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 438, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 260, in get_item
    return await self.get_artist(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 307, in get_artist
    if artist_obj := await get_artist(prov_artist_id=prov_artist_id, headers=self._headers):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 41, in get_artist
    return await asyncio.to_thread(_get_artist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 33, in _get_artist
    artist = ytm.get_artist(channelId=prov_artist_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 220, in get_artist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 230, in _send_request
    headers=self.headers,
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 215, in headers
    self._headers["authorization"] = self._token.as_auth()
                                     ^^^^^^^^^^^
AttributeError: 'YTMusic' object has no attribute '_token'
```

### Additional information

Worked fine on previous version (well, fine besides stopping after one track lol). 

### What version of Home Assistant Core are your running

2023.12.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Just looking at the final error. Did you do the authentication step again when you re-added?

**Comment by benblb** [comment]
Yes I did. Went through the Google auth screens until it told me to "continue on your device" (or similar). Got the same error with both the original and newly added account (same account, just tried re-adding).

**Comment by OzGav** [comment]
If it won’t be too much inconvenience I suggest removing both of those. Then do not reboot the MA host for at least an hour (so the DB can get cleaned up) then restart MA then try adding again.
If that will be too inconvenient then sit tight until this can get looked at more closely although I don’t see any issues reported currently on the ytmusicapi repo

**Comment by benblb** [comment]
Sounds good, thanks. I'll consider the steps above in the meantime. I checked for issues on that repo as well and didn't find anything.

**Comment by yurio** [comment]
I have the same issue after update to 2.0.0b81

**Comment by OzGav** [comment]
@MarvinSchenkel

**Comment by MarvinSchenkel** [comment]
Seems like an auto update of the downstream `ytmusicapi` breaks our authentication. I reverted back to the previous version and will make the changes required to be compatible with the new version soon(ish).

Should be fixed in https://github.com/music-assistant/server/pull/997

**Comment by OzGav** [comment]
Beta 82 has been released which should fix this problem. Please advise if not.

**Comment by benblb** [comment]
Confirmed resolved, thanks so much for the quick fix!
