### ISSUE TITLE
Snapcast players won't play when added to Playergroup

### ISSUE THREAD

**Issue by craigbeat** [music-assistant/hass-music-assistant#3086]
### What version of Music Assistant has the issue?

2.4.0b2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I set up a Playergroup that contains any Snapcast player, the all the devices in that group will play **_except_** for the Snapcast devices. This is true even if the Snapcast device is the only device in the group. If I choose the Snapcast device on it's own (not the group) it works. Here is an example error:
`2024-10-26 10:22:15.465 WARNING (MainThread) [music_assistant] Error while unload provider Snapcast: 'NoneType' object has no attribute 'state'
2024-10-26 10:22:15.471 INFO (MainThread) [music_assistant.snapcast.snapserver] Starting builtin Snapserver...
2024-10-26 10:22:17.490 INFO (MainThread) [music_assistant.snapcast] Started connection to Snapserver 127.0.0.1:1705
2024-10-26 10:22:17.490 INFO (MainThread) [music_assistant] Loaded player provider Snapcast
2024-10-26 10:23:29.029 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/providers/snapcast/__init__.py", line 511, in play_media
    ugp_stream = ugp_provider.ugp_streams[media.queue_id]
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ugp_streams'
2024-10-26 10:23:29.284 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Test generic - crossfade: False`

### How to reproduce

- Enable the 'Playergroup' player provider
- Enable the 'Snapcast' player provider and configure for internal Snapcast server
- Create a new Playergroup and add a Snapcast player (e.g. An android device with the snapcast app installed)
- Select the Snapcast player and play a track to confirm Snapcast is working
- Select the Playergroup you created and try playing the same song

### Music Providers

Tried with both Spotify and YouTube music

### Player Providers

Snapcast
Playergroup

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17529787/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Can you please use the terminology from the docs so we know what you are referring to. There is no GENERIC group in MA

**Comment by craigbeat** [comment]
Updated to remove and replace 'generic' with Playergroup. Thanks.

**Comment by OzGav** [comment]
Have you then used a Snapcast Group or a Universl Group?

**Comment by craigbeat** [comment]
Yes. Snapcast sync groups work on their own as well, but not in Player group / Universal Group.

**Comment by OzGav** [comment]
So you are trying to group snapcast with something else?

**Comment by craigbeat** [comment]
Correct. It's a convoluted set up that started with a Chromecast Audio going to Line-In on a device that then routes that stream via Snapcast. If I put the CCA in a group with the Snapcast devices, I could play to that group and get multi-room audio, and still be able to use the 'Cast' feature.

It has now evolved somewhat that I am only using Snapcast in the garden, but still want the audio in my house at the same time via exeisting Google Audio devices. I don't need it to sync, but I do have a little HA script that runs that pulls Chromecast players in closer sync by checking the seek position of the Snapcast players, and this works if I manually start the multiple player groups, but ideally, having everything in a Universal Playergroup would be more convenient. I've tried using the HA Group, but it doesn't work with the sync script I created.

Thanks again - Music Assistant has been a great help in getting close to where I want to be for my home audio.

**Comment by OzGav** [comment]
@SantiagoSotoC thoughts on universal groups with snapcast?

**Comment by SantiagoSotoC** [comment]
There seems to be a bug in the code, easy to fix, at least according to the log, tomorrow I will try to fix it

**Comment by SantiagoSotoC** [comment]
@marcelveldt , this line
 
`ugp_provider: PlayerGroupProvider = self.mass.get_provider("ugp")
`
 should have to be replaced by the following ? 

`ugp_provider: PlayerGroupProvider = self.mass.get_provider("player_group")
`

**Comment by SantiagoSotoC** [comment]
Should fix the problem : https://github.com/music-assistant/server/pull/1756

**Comment by craigbeat** [comment]
Thank you! The fix works perfectly.
